### ISSUE TITLE
Version 1 Milestone Activities

### ISSUE THREAD

**Issue by thedavidprice** [grwim/grwim.github.io#5]
## High Priority
[v0.20 ] banner title isn't working: too vague & confusing, lacks clarity about what ACRO does in one short sentence.
    - propose "A trusted facilitator of policy for the operation of cloud-connected robots"
    - Karl, is there any other word or concept for "policy"... an idea to wrap all this in?
    - check out the section "The Way Forward" on this page: http://humanetech.com/problem#the-way-forward Note there "4 levers", which feels like we can use this structure and include "policy" as one a several levers
- [p3] "Join us" isn't working for call to action. Suggest we instead offer a newsletter signup "to get notified when ACRO membership is launching". In this case will need:
    - clarity about membership -- what you get
    - clarity about where ACRO is in process of launching
    - add contact info to footer 
    - use mailchimp signup
- [ ] need credibility/testimonial section -- quotes? companies? people? 
- [v0.30] images aren't working: too literal, and "cool" tones convey different emotions than we want, banner makes shape of heart sign which doesn't fit message, two-fingers touching like God/Adam implies philosophical statement
    - short-term: pattern or generic background possible? better to not have strong images than to mis-communicate with the incorrect images
    - long-term: this is hard without yet having a brand, should work on iterating messaging+audience+design options.
- [x] in menu, "Stakeholders" styling and size should match problem and solution  
- [x] need padding above "Robotics has a dirty little secret:"
- [ v0.30] improve Gap Diagram: communication prioritization (i.e. the Gap), and design. See issue #1
- [v0.20 ] Karl, could you work on doing some writing for the "Robotics has a dirty little secret:" section? Could use 2-3 heading with a sentence or two of text each. Currently doesn't flow as well as it could. Not terrible. Just not great. For reference, see this page and all sections: http://humanetech.com/problem/
- [x] who should join section: doesn't read well (both styling and layout issue), let's just make the 4 items a centered, bullet point list

### Layout and Styling
- [p2] padding between sections and text is inconsistent 
- [p2] text styling: improve typography for better readability (especially within sections) -- standardize and padding
### Misc
- [x] Google analytics: account and include script

### SEO
- [p2] google trends analyses for keywords
- [p2] improve meta page title
- [p2] add meta description
- [p2] add meta keywords
- [p2] submit to Google and Bing webmaster tools (create account?)
- [p2] tbd: sitemap in case of multi-page and blog

**Comment by thedavidprice** [comment]
Moving "Beyond v1: Content and Features" list to new issue.

**Comment by thedavidprice** [comment]
moved all these to PRs or individual issues. Closing for now.
